"""Club models

Revision ID: 8803a15ee384
Revises: 797490378b3b
Create Date: 2024-02-13 17:36:55.547882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8803a15ee384'
down_revision = '797490378b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_clubs_book_id_books')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs'))
    )
    op.create_table('clubusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_clubusers_club_id_clubs')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clubusers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubusers'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clubusers')
    op.drop_table('clubs')
    # ### end Alembic commands ###
